// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webApiIFRS.Models;

#nullable disable

namespace webApiIFRS.Migrations
{
    [DbContext(typeof(ConnContext))]
    partial class ConnContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webApiIFRS.Models.Contrato", b =>
                {
                    b.Property<int>("con_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("con_id"));

                    b.Property<int>("con_capacidad_sepultura")
                        .HasColumnType("int");

                    b.Property<int>("con_cuotas_pactadas")
                        .HasColumnType("int");

                    b.Property<int>("con_cuotas_pactadas_mod")
                        .HasColumnType("int");

                    b.Property<int>("con_estado_contrato")
                        .HasColumnType("int");

                    b.Property<DateTime>("con_fecha_ingreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("con_fecha_primer_vcto_ori")
                        .HasColumnType("datetime2");

                    b.Property<int>("con_id_tipo_ingreso")
                        .HasColumnType("int");

                    b.Property<string>("con_nombre_cajero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("con_num_con")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("con_num_repactaciones")
                        .HasColumnType("int");

                    b.Property<int>("con_pie")
                        .HasColumnType("int");

                    b.Property<int>("con_precio_base")
                        .HasColumnType("int");

                    b.Property<int>("con_tasa_interes")
                        .HasColumnType("int");

                    b.Property<string>("con_terminos_pago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("con_tipo_compra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("con_tipo_movimiento")
                        .HasColumnType("int");

                    b.Property<int>("con_total_credito")
                        .HasColumnType("int");

                    b.Property<int>("con_total_venta")
                        .HasColumnType("int");

                    b.Property<int>("con_valor_cuota_pactada")
                        .HasColumnType("int");

                    b.HasKey("con_id");

                    b.ToTable("Contrato");
                });

            modelBuilder.Entity("webApiIFRS.Models.IngresosDiferidos", b =>
                {
                    b.Property<int>("ing_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ing_id"));

                    b.Property<int>("ing_estado_contab")
                        .HasColumnType("int");

                    b.Property<DateTime>("ing_fecha_contab")
                        .HasColumnType("datetime2");

                    b.Property<int>("ing_interes_diferido")
                        .HasColumnType("int");

                    b.Property<int>("ing_nro_cuota")
                        .HasColumnType("int");

                    b.Property<string>("ing_num_con")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ing_precio_base")
                        .HasColumnType("int");

                    b.HasKey("ing_id");

                    b.ToTable("IngresosDiferidos");
                });

            modelBuilder.Entity("webApiIFRS.Models.InteresesPorDevengar", b =>
                {
                    b.Property<int>("int_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("int_id"));

                    b.Property<int>("int_abono_a_capital")
                        .HasColumnType("int");

                    b.Property<int>("int_cuota_final")
                        .HasColumnType("int");

                    b.Property<int>("int_estado_contab")
                        .HasColumnType("int");

                    b.Property<DateTime>("int_fecha_contab")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("int_fecha_vcto")
                        .HasColumnType("datetime2");

                    b.Property<int>("int_nro_cuota")
                        .HasColumnType("int");

                    b.Property<string>("int_num_con")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("int_saldo_final")
                        .HasColumnType("int");

                    b.Property<int>("int_saldo_inicial")
                        .HasColumnType("int");

                    b.Property<int>("int_tasa_interes")
                        .HasColumnType("int");

                    b.HasKey("int_id");

                    b.ToTable("InteresesPorDevengar");
                });
#pragma warning restore 612, 618
        }
    }
}
